- name: Redmineディレクトリ以下のオーナーを変更
  sudo: yes
  file:
    path: "{{ redmine_dir }}"
    owner: "{{ redmine_dir_owner }}"
    group: "{{ redmine_dir_group }}"
    recurse: yes

- name: Passengerがインストールされているか確認
  command:
    test -f /usr/local/bin/passenger-install-apache2-module
  register:
    result
  failed_when: result.rc not in [0, 1]
  changed_when: false

- name: Passengerをインストール
  sudo: yes
  gem:
    name=passenger
    user_install=no
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: result.rc == 1

- name: PassengerのApache用モジュールのインストール
  sudo: yes
  command:
    passenger-install-apache2-module --auto
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: result.rc == 1

- name: PassengerのApache用モジュールの設定を取得
  command:
    passenger-install-apache2-module --snippet
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register:
    passenger_snippet_vars
  changed_when: false

- name: redmine.confの作成
  sudo: yes
  template:
    src=redmine.conf
    dest=/etc/apache2/conf-available/redmine.conf

- name: Redmineに /redmine でアクセスするためのシンボリックリンク作成
  sudo: yes
  file:
    state=link
    src={{ redmine_dir }}/public
    dest=/var/www/html/redmine

- name: Redmine用のApacheの設定を有効にする
  sudo: yes
  command:
    a2enconf redmine

- name: Apacheの再起動
  sudo: yes
  service:
    name=apache2
    state=restarted
    enabled=yes
